### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first

### ISSUE THREAD

**Issue by amir-tagh** [wengong-jin/hgraph2graph#40]
Hello,

I am using the finetune_generator.py and I am getting the following error. does anybody know how to solve this.

Thanks,

Loading from checkpoint ckpt/inforna-pretrained/model.ckpt.5000
After pruning 257 -> 257
Epoch 0 training...
  0%|          | 0/13 [00:25<?, ?it/s]
Traceback (most recent call last):
  File "/apps/hgraph2graph/20210428/hgraph2graph/finetune_generator.py", line 152, in <module>
    meters = meters + np.array([kl_div, loss.item(), wacc * 100, iacc * 100, tacc * 100, sacc * 100])
  File "/apps/hgraph2graph/20210428/lib/python3.7/site-packages/torch/_tensor.py", line 732, in __array__
    return self.numpy()
**TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.**

**Comment by dbhaskar92** [comment]
In `train_generator.py`, change line 96 to:

> meters = meters + np.array([kl_div, loss.item(), wacc.cpu() * 100, iacc.cpu() * 100, tacc.cpu() * 100, sacc.cpu() * 100])

**Comment by amir-tagh** [comment]
Thanks.
