### ISSUE TITLE
TypeError: forward() missing 2 required positional arguments: 'y_orders' and 'beta'

### ISSUE THREAD

**Issue by amir-tagh** [wengong-jin/hgraph2graph#42]
I am using the train_translator.py for lead optimization and I am getting the following error. does anybody know how I can fix this?

Thanks,

Traceback (most recent call last):
  File "/apps/hgraph2graph/20210428/hgraph2graph/train_translator.py", line 86, in <module>
    loss, kl_div, wacc, iacc, tacc, sacc = model(*batch)
  File "/apps/hgraph2graph/20210428/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'y_orders' and 'beta'

**Comment by zhangsan5213** [comment]
I am also running into this issue.

**Comment by Bunnybeibei** [comment]
You can see if you default mode is "pair" when you run process.py. The correct single input format is that each molecule has three pieces of information,  and the pairs input has five pieces of information, because 'x_orders' is not required, as shown in the figure below. [https://tudingtu.cn/i/2023/02/20/in38hi.png](url)
“beta” is the hyperparameter VAE loss, which is used to control the ratio of reconstruction error to KL divergence loss.
